[package]
name = "test_rquest"
version = "0.1.0"
edition = "2021"

[dependencies]
rquest = { version =  "2.1.5", features = ["json", "cookies", "stream","socks"]}
tokio = { version = "1", features = ["full"] }
